### PR TITLE
Changing the size of the signup screen image and modifying the animation

### PR DESCRIPTION
**Pull request by pedrodecf**
image

To default to the signin screen image

And also, I added animation to everything on the page (before it was just on the form)

### CODE REVIEW

**Review by LucSosa — DISMISSED** [review]
this code is aprove, because is a simple modify in image

**Review by LucSosa — APPROVED** [review]
this a simple modify code, to change a image

**Review by LucSosa — DISMISSED** [review]

**Review by LucSosa — DISMISSED** [review]
ok.

**Review by LucSosa — DISMISSED** [review]

**Review by maxyuri13 — APPROVED** [review]
Great job, Pedro.

**Review by maxyuri13 — DISMISSED** [review]

**Review by LucSosa — DISMISSED** [review]
ok

**Pull request closed without merging**
